### ISSUE TITLE
Funzionalità di aumento/riduzione GLOBALE dell'intensità luminosa da riformulare

### ISSUE THREAD

**Issue by pierobonluca01** [SWEasabi/analisi-dei-requisiti#100]
E' presente una funzionalità che non è chiaro se rappresenti una singola area (e in questo caso la funzionalità sarebbe duplicata).

**Comment by bonni1207** [comment]
Quale UC è?

**Comment by pierobonluca01** [comment]
> Quale UC è?

E' [questa](https://github.com/SWEasabi/analisi-dei-requisiti/blob/0855566c5b70599a5287f4aade3aa9553bae7e61/src-doc/contenuti/introduzione.tex#L24) funzionalità.

**Comment by bonni1207** [comment]
> > Quale UC è?
> 
> E' [questa](https://github.com/SWEasabi/analisi-dei-requisiti/blob/0855566c5b70599a5287f4aade3aa9553bae7e61/src-doc/contenuti/introduzione.tex#L24) funzionalità.

Secondo me, come è scritta ora è duplicata con quella precedente.
Forse dovrebbero essere:
Aumento o riduzione manuale dell'intensità luminosa di un lampione;
Aumento o riduzione globale dell'intensità luminosa di un'area illuminata;

@alessandro-massarenti te cosa ne pensi?

**Comment by pierobonluca01** [comment]
> > > Quale UC è?
> > 
> > 
> > E' [questa](https://github.com/SWEasabi/analisi-dei-requisiti/blob/0855566c5b70599a5287f4aade3aa9553bae7e61/src-doc/contenuti/introduzione.tex#L24) funzionalità.
> 
> Secondo me, come è scritta ora è duplicata con quella precedente. Forse dovrebbero essere: Aumento o riduzione manuale dell'intensità luminosa di un lampione; Aumento o riduzione globale dell'intensità luminosa di un'area illuminata;
> 
> @alessandro-massarenti te cosa ne pensi?

Anche secondo me, magari specificando che la modifica della luminosità in modo globale avviene in modo automatico.

**Comment by bonni1207** [comment]
> > > > Quale UC è?
> > > 
> > > 
> > > E' [questa](https://github.com/SWEasabi/analisi-dei-requisiti/blob/0855566c5b70599a5287f4aade3aa9553bae7e61/src-doc/contenuti/introduzione.tex#L24) funzionalità.
> > 
> > 
> > Secondo me, come è scritta ora è duplicata con quella precedente. Forse dovrebbero essere: Aumento o riduzione manuale dell'intensità luminosa di un lampione; Aumento o riduzione globale dell'intensità luminosa di un'area illuminata;
> > @alessandro-massarenti te cosa ne pensi?
> 
> Anche secondo me, magari specificando che la modifica della luminosità globale avviene in modo automatico.

La modifica globale non può avvenire in manuale? Tipo viene settato un valore manualmente, che poi setta tutti i singoli lampioni.

**Comment by Giorgio-Zarantonello** [comment]
Si e' arrivati ad una soluzione su come cambiare ? che procedo

**Comment by alessandro-massarenti** [comment]
> > > Quale UC è?
> > 
> > 
> > E' [questa](https://github.com/SWEasabi/analisi-dei-requisiti/blob/0855566c5b70599a5287f4aade3aa9553bae7e61/src-doc/contenuti/introduzione.tex#L24) funzionalità.
> 
> Secondo me, come è scritta ora è duplicata con quella precedente. Forse dovrebbero essere: Aumento o riduzione manuale dell'intensità luminosa di un lampione; Aumento o riduzione globale dell'intensità luminosa di un'area illuminata;
> 
> @alessandro-massarenti te cosa ne pensi?

Non è duplicata, è solo scritta da cani.

La funzionalità:
`Aumento o riduzione manuale dell’intensità luminosa in un’area illuminata;`
si sipiega da sola

La funzionalità:
`Aumento o riduzione globale dell’intensità luminosa;`
intende che il sistema deve poter cambiare l'intensità luminosa di più lampioni a gruppi.
Sia automaticamente che manualmente.

Tendenzialmente la prima potrebbe essere relativizzata ad un solo lampione.

Detto questo, queste erano le funzionalità descritte nel capitolato:
![image](https://user-images.githubusercontent.com/48263116/222966503-77014e60-d855-4793-8e5c-e36e1ca839c3.png)

e sicuramente si possono riscrivere meglio ma sarebbero da lasciare il più possibile a "parole del capitolato" magari aggiungendo una descrizione in un modo consono.

**Comment by alessandro-massarenti** [comment]
https://github.com/SWEasabi/analisi-dei-requisiti/blob/c69e0a0bc86f3bfe3b937a151eba53d32787b113/src-doc/contenuti/requisiti.tex#L57 Consiglio la visione anche di questo requisito

**Comment by alessandro-massarenti** [comment]
Vedasi linea https://github.com/SWEasabi/analisi-dei-requisiti/blob/dfd16a230b06669ed31074c73136aba8bb883027/src-doc/contenuti/requisiti.tex#L51

**Comment by alessandro-massarenti** [comment]
In conclusione si può aggiungere la footnote con scritto "Questa funzionalità intende che l'utente deve poter regolare contemporaneamente l'intensità luminosa di tutti i lampioni nel sistema, vedasi <<Riferimento a RF_13 usando i comandi latex>>"
