### ISSUE TITLE
requisiti funzionali

### ISSUE THREAD

**Issue by bonni1207** [SWEasabi/analisi-dei-requisiti#102]

**Comment by alessandro-massarenti** [comment]
Si consiglia la visione di https://docs.google.com/spreadsheets/d/1FqJytLJuJUthM4z_Vv9_REoctpGnlWgJVdL7qV3EFzs/edit#gid=0

**Comment by alessandro-massarenti** [comment]
Nell'ultimo commit, https://github.com/SWEasabi/analisi-dei-requisiti/commit/6b86ad4b42a74b1af9f95b6db5b48e5661e648ba ho aggiunto un todo @casYy .

Non mi fido di come è steso un requisito nel foglio google.
