### ISSUE TITLE
Manca il requisito relativo al logging

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#124]
Vedasi Capitolato e Specifica architetturale.

Valutare se manca anche in altre parti del documento.

Vediamo assieme se aggiungere la cosa nel documento oppure no.

**Comment by alessandro-massarenti** [comment]
ok, ma manca comunque un requisito copra il caso d'uso UC05

**Comment by alessandro-massarenti** [comment]
@casYy tu cosa dici? Potresti darci un occhio?

**Comment by casYy** [comment]
E' vero manca il req. Immagino si possa fare un requisito funzionale "L'utente deve poter essere in grado di visualizzare i dettagli di un lampione" o una roba simile.
