### ISSUE TITLE
Prima Bozza "Vincoli di progettazione"

### ISSUE THREAD

**Issue by casYy** [SWEasabi/analisi-dei-requisiti#48]
Scrivere una prima bozza della sezione "Vincoli di progettazione" (possibilmente in tabella, si tratta di specificare quali tecnologie sono state richieste dall'azienda per diverse parti della piattaforma).

**Comment by casYy** [comment]
Il nome del file dovrebbe essere "vincoli-di-progettazione"

**Comment by alessandro-massarenti** [comment]
@casYy Ho visto che "vincoli di progettazione" è un capitolo, ma probabilmente sarebbe meglio:
- creare un capitolo chiamato "descrizione generale" o qualcosa sulla stessa rotta
- spostare al suo interno i vincoli di progettazione obbligatori ed opzionali
- spostare al suo interno gli obiettivi del prodotto issue #46 
- spostare al suo interno tutte le altre informazioni descrittive. 

L'idea è di creare un file per ogni sezione? forse sarebbe meglio un file per ogni capitolo in modo da non frammentare esageratamente il sorgente.

**Comment by alessandro-massarenti** [comment]
Prima della descrizione delle tecnologie inoltre sarebbe più interessante descrivere quali sono gli scopi del prodotto, solo allora sarà possibile analizzare le tecnologie da utilizzare.

**Comment by casYy** [comment]
> @casYy Ho visto che "vincoli di progettazione" è un capitolo, ma probabilmente sarebbe meglio:
> 
>     * creare un capitolo chiamato "descrizione generale" o qualcosa sulla stessa rotta
> 
>     * spostare al suo interno i vincoli di progettazione obbligatori ed opzionali
> 
>     * spostare al suo interno gli obiettivi del prodotto issue [Scrivere prima bozza "Obiettivi del prodotto" #46](https://github.com/SWEasabi/analisi-dei-requisiti/issues/46)
> 
>     * spostare al suo interno tutte le altre informazioni descrittive.
> 
> 
> L'idea è di creare un file per ogni sezione? forse sarebbe meglio un file per ogni capitolo in modo da non frammentare esageratamente il sorgente.

Sì sono abbastanza d'accordo in linea generale
