### ISSUE TITLE
Sarebbero da aggiungere intestazione e pie di pagina

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#58]
Date le considerevoli dimensioni del documento sarebbe interessante ed importante inserire un'intestazione alle pagine.
Questo con lo scopo di aiutare il lettore a mantenere traccia della posizione e di che documento si sta parlando.

**Comment by casYy** [comment]
@romano001 crea un branch fix/... per lavorarci.

**Comment by alessandro-massarenti** [comment]
> @romano001 crea un branch fix/... per lavorarci.

Fix? è una feature aggiunta questa, volendo me ne occupo io

**Comment by romano001** [comment]
Non avendo mai fatto una cosa del genere mi servirebbe qualche dritta, comunque posso occuparmene io (purtroppo non riesco nell'immediato)

**Comment by casYy** [comment]
Nessun problema, possiamo lasciarlo ad alessandro.
