### ISSUE TITLE
All'analisi andrebbe aggiunto un paragrafo sull'interazione tra i componenti

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#67]
Discutendo con Lorenzo si è notato come andrebbe aggiunto un paragrafo sull'interazione tra i componenti.

In questo modo si potrebbe accennare all'utilizzo di un layer rest_api senza discuterne l'implementazione specifica.

**Comment by casYy** [comment]
Lo mettiamo nel secondo capitolo o parli di fare un capitolo a parte?

**Comment by alessandro-massarenti** [comment]
Forse sarebbe da iniziare a stendere una scaletta di base sulla quale basarsi in modo da non gestire ogni feature/issue singolarmente.

In generale farei un capitolo relativo a queste sezioni aggiuntive. magari sotto la descrizione dei casi d'uso.

**Comment by alessandro-massarenti** [comment]
Ragionando con il professore aggiungere questo paragrafo all'analisi dei requisiti non è una buona idea, infatti queste sono questioni implementative e andranno probabilmente affrontate nell'ambito del documento di specifica architetturale.

Il consiglio è soprattutto di rivedere lo studio dei casi d'uso.
