### ISSUE TITLE
coordinator_service o backend_api come attore secondario?

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#68]
Avrebbe più senso scrivere coordinator_service o backend_api come attore secondario?

Contando che poi probabilmente tutte le chiamate passeranno attraverso quel livello, o anche in questo caso conviene solo descriverlo nella sezione "interazione tra i componenti". vedi: #67 

Probabilmente sarà bene scrivere una e-mail al professore.

**Comment by casYy** [comment]
Sentiamo l'opinione del professore per ora

**Comment by alessandro-massarenti** [comment]
Come da ragionamenti con il professore questa questione è da analizzare in un altro documento, non nell'analisi dei requisiti.
Probabilmente se ne parlerà nel momento della stesura della specifica architetturale.
