### ISSUE TITLE
Sistemare i casi d'uso dopo visione professore

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#80]
Nella prima stesura grafica dei casi d'uso fatta ci sono parecchi errori sintattici.

Si necessita una review completa dei casi d'uso per ridefinire più correttamente gli stessi

**Comment by alessandro-massarenti** [comment]
Stendendo la nuova revisione a livello testuale mi sono accorto che probabilmente mancano i seguenti UC(In corsivo quelli che mi rendono più dubbioso)

- Inserimento di nuovi utenti
- _Gestione di nuovi utenti_
- Visualizzazione dei ticket aperti(Almeno relativamente ad un sensore o ad un lampione)

Manca inoltre la parte relativamente al logging dei dati, richiesta dal capitolato.

**Comment by alessandro-massarenti** [comment]
Probabilmente conviene accorpare uc 18 ad uc17, @bonni1207 cosa ne pensi?

**Comment by bonni1207** [comment]
Si anche secondo me uc17 e uc18 sono da accorpare, magari in "Cambiamento luminosità lampione" o qualcosa del genere

**Comment by bonni1207** [comment]
Si anche io penso sia meglio accorpare uc17 e uc18, magari in un "Cambiamento luminosità lampione", o qualcosa di simile.
Stessa cosa per uc19 e uc20

**Comment by alessandro-massarenti** [comment]
Aprirei allora una issue relativamente a questo commento.

> Si anche io penso sia meglio accorpare uc17 e uc18, magari in un "Cambiamento luminosità lampione", o qualcosa di simile. Stessa cosa per uc19 e uc20

È inoltre da aprire un'altra issue relativa al sistema "applicazione, illuminazione".

UC19(La nuova uc accorpata ha come attore primario anche utente gestore)
