### ISSUE TITLE
Probabilmente mancano i seguenti UC

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#84]
Mancano i seguenti UC nella nuova ridefinizione e stesura, ma vorrei essere sicuro prima di definirne una stesura

> Stendendo la nuova revisione a livello testuale mi sono accorto che probabilmente mancano i seguenti UC(In corsivo quelli che mi rendono più dubbioso)
> 
> 1. Inserimento di nuovi utenti
> 2. _Gestione di nuovi utenti_
> 3. Visualizzazione dei ticket aperti(Almeno relativamente ad un sensore o ad un lampione)
> 
> Manca inoltre la parte relativamente al logging dei dati, richiesta dal capitolato.
> 
> _Originally posted by @alessandro-massarenti in [#80 (comment)](https://github.com/SWEasabi/analisi-dei-requisiti/issues/80#issuecomment-1385303310)_

Da capitolato:

1. Altrimenti gli utenti sarebbero sovra-imposti dall'alto e non ha troppissimo senso
2. Come punto 1
3. Da capitolato: <img width="317" alt="image" src="https://user-images.githubusercontent.com/48263116/213478519-7cd3b9a1-3124-44b7-b4e8-f006d5b06b51.png">

**Comment by alessandro-massarenti** [comment]
Riguardando il capitolato ho notato che mancano tra i casi d'uso anche cose come:

- Tracciamento delle intensità luminose di ogni impianto: <img width="308" alt="image" src="https://user-images.githubusercontent.com/48263116/213479280-24e7a8a4-6247-4a17-8034-6dfaf7138495.png">
- Modifica delle aree illuminate(Probabilmente di campi come nome, e informazioni sulla posizione), aggiunta e rimozione di lampioni dalle aree invece è già definito dagli uc10 e uc11

**Comment by Giorgio-Zarantonello** [comment]
Approvo le motivazioni dette da @alessandro-massarenti , ritengo anche io che questi UC siano mancanti

**Comment by casYy** [comment]
3 assolutamente sì, 1 e 2 non sono necessarie

**Comment by alessandro-massarenti** [comment]
> 3 assolutamente sì, 1 e 2 non sono necessarie da capitolato

Si, giustamente il capitolato ci fa capire che a noi basta avere un "utente" per tipo e siamo a posto.

**Comment by bonni1207** [comment]
Ho aggiunto i casi d'uso di visualizzazione all'utente gestore:
- uc2
- uc3
- uc4
- uc5
Ricordarsi di aggiungerli alla descrizione testuale.
