### ISSUE TITLE
Tracciamento delle intensità luminose di ogni impianto

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#85]
Riguardando il capitolato ho notato che mancano tra i casi d'uso anche cose come:

- Tracciamento delle intensità luminose di ogni impianto: <img width="308" alt="image" src="https://user-images.githubusercontent.com/48263116/213479280-24e7a8a4-6247-4a17-8034-6dfaf7138495.png">

_Originally posted by @alessandro-massarenti in https://github.com/SWEasabi/analisi-dei-requisiti/issues/84#issuecomment-1397131557_

**Comment by alessandro-massarenti** [comment]
@Giorgio-Zarantonello Ecco, ti ho aperto la issue relativamente al tracciamento delle intensità luminose di ogni area.

Probabilmente questa funzionalità sarà composta da più issue, ti consiglio di proporre qui una prima draft(anche senza descrizione testuale) così vediamo se matcha con il resto dei casi d'uso già stilati.

**Comment by alessandro-massarenti** [comment]
Visto il [capitolato](https://www.math.unipd.it/~tullio/IS-1/2022/Progetto/C2.pdf) stilerei così gli uc:

Attore primario utente gestore/utente manutentore:
- UCA - Visualizzazione dell'intensità luminosa di un lampione nel tempo
Attore primario Lampadina:
- UCB - Inserimento dato dell'intensità luminosa

@bonni1207 Cosa ne pensi? aggiungeresti altro?

**Comment by bonni1207** [comment]
Secondo me vanno bene.
UCB, verrà attivata da un trigger ogni tot tempo

**Comment by alessandro-massarenti** [comment]
> Secondo me vanno bene, non aggiungerei altro. UCB, verrà attivata da un trigger ogni tot tempo

Forse sarebbe ancora meglio dire "Visualizzazione dell'intensità luminosa dell'area" invece che "del lampione", cosa ne pensi?

**Comment by bonni1207** [comment]
Si, meglio area
