### ISSUE TITLE
Stilare casi d'uso relativi alla modifica delle aree illuminate

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#86]
>              Riguardando il capitolato ho notato che mancano tra i casi d'uso anche cose come:
>
>- Modifica delle aree illuminate(Probabilmente di campi come nome, e informazioni sulla posizione), aggiunta e rimozione di >lampioni dalle aree invece è già definito dagli uc10 e uc11
>
>_Originally posted by @alessandro-massarenti in https://github.com/SWEasabi/analisi-dei->requisiti/issues/84#issuecomment-1397131557_

Vanno stilati i casi d'uso relativi alle funzionalità di modifica delle aree illuminate.

**Comment by alessandro-massarenti** [comment]
Delle aree illuminate modificherei solo il nome, che altre funzionalità di modifica dareste voi, @bonni1207 @pierobonluca01 ?

Chiaramente sto sottointendendo l'aggiunta e rimozione dei lampioni.

**Comment by casYy** [comment]
@alessandro-massarenti per quanto riguarda le "informazioni sulla posizione", come vengono gestite? coordinate? indirizzo?

**Comment by alessandro-massarenti** [comment]
> @alessandro-massarenti per quanto riguarda le "informazioni sulla posizione", come vengono gestite? coordinate? indirizzo?

In generale userei una posizione nominativa e nulla più. Dimmi anche tu cosa ne pensi.
