### ISSUE TITLE
Aggiungere modifiche al registro dei cambiamenti per il rilascio della versione 0.0.4

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/analisi-dei-requisiti#88]
Per rilasciare la versione 0.0.4 è d'obbligo aggiungere le informazioni al registro dei cambiamenti.

**Comment by casYy** [comment]
- Riordinate uc
- Fatte immagini casi d'uso in migliore definizione
- UC tracciamento intensità luminose (19 e 5.1)
- UC visualizzazione ticket (18,20)
- Correzione e aggiunta sottouc a UC2
- UC modifica area luminosa (UC23,24,25)

**Comment by alessandro-massarenti** [comment]
Sono stati anche fatti i rewrite di tutte le altre uc della versione 0.0.3 del documento di analisi

**Comment by bonni1207** [comment]
Ho riordinato tutte le uc:
18->07
20->08
07->09
08->10
09->11
10->12
11->13
12->14
13->15
23->16
24->17
25->18
26->19
14->20
15->21
16->22
17->23
19->24
21->25
22->26
le altre sono rimaste invariate.

**Comment by alessandro-massarenti** [comment]
Bisogna aggiungere anche @alessandro-massarenti , @pierobonluca01 @bonni1207 ai verificatori
