### ISSUE TITLE
Aggiungere sezione relativa ai requisiti

### ISSUE THREAD

**Issue by bonni1207** [SWEasabi/analisi-dei-requisiti#89]
Saranno presenti
- [ ] #102
- [ ] #103
- [ ] #104
- [ ] riepilogo generale

**Comment by casYy** [comment]
@alessandro-massarenti @bonni1207 mi sembra troppo grande per essere una singola issue: splitterei ciascun requisito in una singola issue se per voi va bene.

**Comment by alessandro-massarenti** [comment]
> @alessandro-massarenti @bonni1207 mi sembra troppo grande per essere una singola issue: splitterei ciascun requisito in una singola issue se per voi va bene.

Si, assolutamente. Sono da definire bene le parti precedenti e poi da quelli quali sono.

Definiti esattamente splittiamo assolutamente in più issue.

**Comment by casYy** [comment]
> > @alessandro-massarenti @bonni1207 mi sembra troppo grande per essere una singola issue: splitterei ciascun requisito in una singola issue se per voi va bene.
> 
> Si, assolutamente. Sono da definire bene le parti precedenti e poi da quelli quali sono.
> 
> Definiti esattamente splittiamo assolutamente in più issue.

Penso questi 4 elementi siano già dividibili in singole issue per il momento - in caso possiamo aggiungerne altre più avanti.
