### ISSUE TITLE
TODO - Aggiungere le nuove immagini degli UC

### ISSUE THREAD

**Issue by pierobonluca01** [SWEasabi/analisi-dei-requisiti#93]

**Comment by bonni1207** [comment]
Questo è il file .svg da cui prendere le immagini singole:
[casi_uso_grafici](https://user-images.githubusercontent.com/44138357/217593741-fce17b8f-0005-476f-bd60-4d20a6faa3a7.svg)

**Comment by bonni1207** [comment]
Mando su discord il file svg con le immagini singole

**Comment by bonni1207** [comment]
Sistemate tutte le immagini, con gli zeri
