### ISSUE TITLE
Aggiungere "impianto" al glossario

### ISSUE THREAD

**Issue by pierobonluca01** [SWEasabi/analisi-dei-requisiti#98]
La parola "impianto" usata nelle user stories non è chiara.

**Comment by alessandro-massarenti** [comment]
Di solito Impianto viene usato al posto di Lampione.

Probabilmente conviene rimuovere impianto e lasciare solo lampione.
Immagino l'idea iniziale fosse che un intero impianto potesse essere controllato da uno stesso controller, però per semplicità ridurrei a Lampione e tanti saluti.

**Comment by bonni1207** [comment]
Concordo. @pierobonluca01 te cosa dici?

**Comment by pierobonluca01** [comment]
Segue la mia idea principale, per me va bene.

**Comment by bonni1207** [comment]
Allora dopo procedo.
